### ISSUE TITLE
Playlist labels doesn't showing

### ISSUE THREAD

**Issue by User094573** [duffey/spicetify-playlist-labels#29] opened 2024-04-23 16:23 UTC
On two different computers with slightly different set of spicetify extensions, theme and snippets.
<details>
<summary>Here's the json export of spicetify settings  from my Windows machine.</summary>

```jsonc
{
  "marketplace:installed:snippet:Fix-now-playing-icon-color": "{\"code\":\".main-trackList-playingIcon { -webkit-mask-image: url(\\\"data:image/svg+xml,%3Csvg id='playing-icon' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 22 24'%3E%3Cdefs%3E%3Cstyle%3E %23playing-icon %7B fill: %2320BC54; %7D @keyframes play %7B 0%25 %7Btransform: scaleY(1);%7D 3.3%25 %7Btransform: scaleY(0.9583);%7D 6.6%25 %7Btransform: scaleY(0.9166);%7D 9.9%25 %7Btransform: scaleY(0.8333);%7D 13.3%25 %7Btransform: scaleY(0.7083);%7D 16.6%25 %7Btransform: scaleY(0.5416);%7D 19.9%25 %7Btransform: scaleY(0.4166);%7D 23.3%25 %7Btransform: scaleY(0.25);%7D 26.6%25 %7Btransform: scaleY(0.1666);%7D 29.9%25 %7Btransform: scaleY(0.125);%7D 33.3%25 %7Btransform: scaleY(0.125);%7D 36.6%25 %7Btransform: scaleY(0.1666);%7D 39.9%25 %7Btransform: scaleY(0.1666);%7D 43.3%25 %7Btransform: scaleY(0.2083);%7D 46.6%25 %7Btransform: scaleY(0.2916);%7D 49.9%25 %7Btransform: scaleY(0.375);%7D 53.3%25 %7Btransform: scaleY(0.5);%7D 56.6%25 %7Btransform: scaleY(0.5833);%7D 59.9%25 %7Btransform: scaleY(0.625);%7D 63.3%25 %7Btransform: scaleY(0.6666);%7D 66.6%25 %7Btransform: scaleY(0.6666);%7D 69.9%25 %7Btransform: scaleY(0.6666);%7D 73.3%25 %7Btransform: scaleY(0.6666);%7D 76.6%25 %7Btransform: scaleY(0.7083);%7D 79.9%25 %7Btransform: scaleY(0.75);%7D 83.3%25 %7Btransform: scaleY(0.8333);%7D 86.6%25 %7Btransform: scaleY(0.875);%7D 89.9%25 %7Btransform: scaleY(0.9166);%7D 93.3%25 %7Btransform: scaleY(0.9583);%7D 96.6%25 %7Btransform: scaleY(1);%7D %7D %23bar1 %7B transform-origin: bottom; animation: play 0.9s -0.51s infinite; %7D %23bar2 %7B transform-origin: bottom; animation: play 0.9s infinite; %7D %23bar3 %7B transform-origin: bottom; animation: play 0.9s -0.15s infinite; %7D %23bar4 %7B transform-origin: bottom; animation: play 0.9s -0.75s infinite; %7D %3C/style%3E%3C/defs%3E%3Ctitle%3Eplaying-icon%3C/title%3E%3Crect id='bar1' class='cls-1' width='4' height='24'/%3E%3Crect id='bar2' class='cls-1' x='6' width='4' height='24'/%3E%3Crect id='bar3' class='cls-1' x='12' width='4' height='24'/%3E%3Crect id='bar4' class='cls-1' x='18' width='4' height='24'/%3E%3C/svg%3E\\\"); background: var(--spice-button); content-visibility: hidden; -webkit-mask-repeat: no-repeat; }\",\"title\":\"Fix now playing icon color\",\"description\":\"Fixes the now playing icon color\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/fix-now-playing-icon.png\"}",
  "marketplace:installed:spicetify/spicetify-cli/Extensions/keyboardShortcut.js": "{\"manifest\":{\"name\":\"Keyboard Shortcut\",\"description\":\"Register some useful keybinds to support keyboard-driven navigation in Spotify client. Less time touching the mouse.\",\"preview\":\"https://i.imgur.com/evkGv9q.png\",\"main\":\"Extensions/keyboardShortcut.js\"},\"type\":\"extension\",\"title\":\"Keyboard Shortcut\",\"subtitle\":\"Register some useful keybinds to support keyboard-driven navigation in Spotify client. Less time touching the mouse.\",\"authors\":[{\"name\":\"spicetify\",\"url\":\"https://github.com/spicetify\"}],\"user\":\"spicetify\",\"repo\":\"spicetify-cli\",\"branch\":\"master\",\"imageURL\":\"https://i.imgur.com/evkGv9q.png\",\"extensionURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-cli/master/Extensions/keyboardShortcut.js\",\"readmeURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-cli/master/undefined\",\"stars\":16365,\"lastUpdated\":\"2024-03-23T00:46:03Z\",\"created\":\"2018-12-01T19:55:18Z\"}",
  "marketplace:installed-extensions": "[\"marketplace:installed:theRealPadster/spicetify-hide-podcasts/hidePodcasts.js\",\"marketplace:installed:Tetrax-10/Spicetify-Extensions/Image-Opener/imageOpener.js\",\"marketplace:installed:spicetify/spicetify-cli/Extensions/keyboardShortcut.js\",\"marketplace:installed:spicetify/spicetify-cli/Extensions/shuffle+.js\",\"marketplace:installed:spicetify/spicetify-cli/Extensions/trashbin.js\",\"marketplace:installed:BlafKing/spicetify-cat-jam-synced/marketplace/cat-jam.js\",\"marketplace:installed:Pithaya/spicetify-apps/extensions/made-for-you-shortcut/dist/made-for-you-shortcut.js\",\"marketplace:installed:duffey/spicetify-playlist-labels/dist/spicetify-playlist-labels.js\",\"marketplace:installed:ohitstom/spicetify-extensions/quickQueue/quickQueue.js\"]",
  "marketplace:installed:ohitstom/spicetify-extensions/quickQueue/quickQueue.js": "{\"manifest\":{\"name\":\"Quick Queue\",\"description\":\"Adds a button to the tracklist to add/remove a song from the queue.\",\"preview\":\"quickQueue/marketplace.png\",\"main\":\"quickQueue/quickQueue.js\",\"readme\":\"quickQueue/README.md\",\"tags\":[\"songs\",\"utility\"]},\"type\":\"extension\",\"title\":\"Quick Queue\",\"subtitle\":\"Adds a button to the tracklist to add/remove a song from the queue.\",\"authors\":[{\"name\":\"ohitstom\",\"url\":\"https://github.com/ohitstom\"}],\"user\":\"ohitstom\",\"repo\":\"spicetify-extensions\",\"branch\":\"main\",\"imageURL\":\"https://raw.githubusercontent.com/ohitstom/spicetify-extensions/main/quickQueue/marketplace.png\",\"extensionURL\":\"https://raw.githubusercontent.com/ohitstom/spicetify-extensions/main/quickQueue/quickQueue.js\",\"readmeURL\":\"https://raw.githubusercontent.com/ohitstom/spicetify-extensions/main/quickQueue/README.md\",\"stars\":28,\"lastUpdated\":\"2024-04-17T01:20:20Z\",\"created\":\"2023-05-12T00:35:27Z\"}",
  "marketplace:installed:BlafKing/spicetify-cat-jam-synced/marketplace/cat-jam.js": "{\"manifest\":{\"name\":\"Cat-Jam Synced\",\"description\":\"An extension that lets a cat jam in sync with the beat of your music.\",\"preview\":\"marketplace/preview.gif\",\"main\":\"marketplace/cat-jam.js\",\"readme\":\"README.md\"},\"type\":\"extension\",\"title\":\"Cat-Jam Synced\",\"subtitle\":\"An extension that lets a cat jam in sync with the beat of your music.\",\"authors\":[{\"name\":\"BlafKing\",\"url\":\"https://github.com/BlafKing\"}],\"user\":\"BlafKing\",\"repo\":\"spicetify-cat-jam-synced\",\"branch\":\"main\",\"imageURL\":\"https://raw.githubusercontent.com/BlafKing/spicetify-cat-jam-synced/main/marketplace/preview.gif\",\"extensionURL\":\"https://raw.githubusercontent.com/BlafKing/spicetify-cat-jam-synced/main/marketplace/cat-jam.js\",\"readmeURL\":\"https://raw.githubusercontent.com/BlafKing/spicetify-cat-jam-synced/main/README.md\",\"stars\":10,\"lastUpdated\":\"2024-04-05T22:57:31Z\",\"created\":\"2024-03-31T15:12:58Z\"}",
  "marketplace:installed:JulienMaille/spicetify-dynamic-theme/user.css": "{\"manifest\":{\"name\":\"Default Dynamic\",\"description\":\"A theme for Spicetify with support for light/dark modes and album art based colors.\",\"preview\":\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/Dark.gif\",\"readme\":\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/README.md\",\"tags\":[\"содержит JS\",\"dynamic-color\",\"flat\"],\"usercss\":\"user.css\",\"schemes\":\"color.ini\",\"include\":[\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/default-dynamic.js\",\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/Vibrant.min.js\"]},\"type\":\"theme\",\"title\":\"Default Dynamic\",\"subtitle\":\"A theme for Spicetify with support for light/dark modes and album art based colors.\",\"authors\":[{\"name\":\"JulienMaille\",\"url\":\"https://github.com/JulienMaille\"}],\"user\":\"JulienMaille\",\"repo\":\"spicetify-dynamic-theme\",\"branch\":\"main\",\"imageURL\":\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/Dark.gif\",\"readmeURL\":\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/README.md\",\"stars\":232,\"tags\":[\"содержит JS\",\"содержит JS\",\"dynamic-color\",\"flat\"],\"cssURL\":\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/user.css\",\"schemesURL\":\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/color.ini\",\"include\":[\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/default-dynamic.js\",\"https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/main/Vibrant.min.js\"],\"schemes\":{\"Base\":{\"animation\":\"010101\"},\"NoAnimation\":{\"animation\":\"000000\"}},\"activeScheme\":\"Base\",\"lastUpdated\":\"2024-04-21T15:01:30Z\",\"created\":\"2021-05-13T19:15:08Z\"}",
  "marketplace:installed:snippet:Hide-now-playing-view-button": "{\"code\":\"button:has(path[d='M11.196 8 6 5v6l5.196-3z'], path[d='.966.783 1.75 1.75 1.75h10.5a1.75']) {display: none;}\",\"title\":\"Hide now playing view button\",\"description\":\"Hides the now playing view button from the playbar\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-now-playing-view-button.png\"}",
  "marketplace:installed:Pithaya/spicetify-apps/extensions/made-for-you-shortcut/dist/made-for-you-shortcut.js": "{\"manifest\":{\"name\":\"\\\"Made for you\\\" shortcut\",\"description\":\"Add a shortcut to the \\\"Made for you\\\" page to the sidebar.\",\"preview\":\"extensions/made-for-you-shortcut/preview.png\",\"main\":\"extensions/made-for-you-shortcut/dist/made-for-you-shortcut.js\",\"readme\":\"extensions/made-for-you-shortcut/README.md\"},\"type\":\"extension\",\"title\":\"\\\"Made for you\\\" shortcut\",\"subtitle\":\"Add a shortcut to the \\\"Made for you\\\" page to the sidebar.\",\"authors\":[{\"name\":\"Pithaya\",\"url\":\"https://github.com/Pithaya\"}],\"user\":\"Pithaya\",\"repo\":\"spicetify-apps\",\"branch\":\"main\",\"imageURL\":\"https://raw.githubusercontent.com/Pithaya/spicetify-apps/main/extensions/made-for-you-shortcut/preview.png\",\"extensionURL\":\"https://raw.githubusercontent.com/Pithaya/spicetify-apps/main/extensions/made-for-you-shortcut/dist/made-for-you-shortcut.js\",\"readmeURL\":\"https://raw.githubusercontent.com/Pithaya/spicetify-apps/main/extensions/made-for-you-shortcut/README.md\",\"stars\":34,\"lastUpdated\":\"2024-04-12T21:00:45Z\",\"created\":\"2022-11-23T14:46:37Z\"}",
  "marketplace:installed:spicetify/spicetify-cli/Extensions/shuffle+.js": "{\"manifest\":{\"name\":\"Shuffle+\",\"description\":\"Shuffles using Fisher–Yates algorithm with zero bias. After installing extensions, right click album/playlist/artist item, there will be an option \\\"Play with Shuffle+\\\". You can also multiple select tracks and choose to \\\"Play with Shuffle+\\\". Moreover, enable option \\\"Auto Shuffle+\\\" in Profile menu to inject Shuffle+ into every play buttons, no need to right click anymore.\",\"preview\":\"https://i.imgur.com/gxbnqSN.png\",\"main\":\"Extensions/shuffle+.js\"},\"type\":\"extension\",\"title\":\"Shuffle+\",\"subtitle\":\"Shuffles using Fisher–Yates algorithm with zero bias. After installing extensions, right click album/playlist/artist item, there will be an option \\\"Play with Shuffle+\\\". You can also multiple select tracks and choose to \\\"Play with Shuffle+\\\". Moreover, enable option \\\"Auto Shuffle+\\\" in Profile menu to inject Shuffle+ into every play buttons, no need to right click anymore.\",\"authors\":[{\"name\":\"spicetify\",\"url\":\"https://github.com/spicetify\"}],\"user\":\"spicetify\",\"repo\":\"spicetify-cli\",\"branch\":\"master\",\"imageURL\":\"https://i.imgur.com/gxbnqSN.png\",\"extensionURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-cli/master/Extensions/shuffle+.js\",\"readmeURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-cli/master/undefined\",\"stars\":16365,\"lastUpdated\":\"2024-03-23T00:46:03Z\",\"created\":\"2018-12-01T19:55:18Z\"}",
  "marketplace:installed:snippet:Remove-Popular-sections-from-homepage": "{\"code\":\".main-shelf-shelf.Shelf:has(> div > div > .main-shelf-seeAll[href='/section/0JQ5DAuChZYPe9iDhh2mJz'], [href='/section/0JQ5DAnM3wGh0gz1MXnu4h'], [href='/section/0JQ5DAnM3wGh0gz1MXnu3B'],[href='/section/0JQ5DAnM3wGh0gz1MXnu3D']) { display: none !important; }\",\"title\":\"Remove Popular sections from homepage\",\"description\":\"Thanks Spotify, but I have a music taste\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/remove-popular.png\"}",
  "marketplace:sort": "lastUpdated",
  "marketplace:tabs": "[{\"name\":\"Extensions\",\"enabled\":true},{\"name\":\"Themes\",\"enabled\":true},{\"name\":\"Snippets\",\"enabled\":true},{\"name\":\"Apps\",\"enabled\":true},{\"name\":\"Installed\",\"enabled\":true}]",
  "marketplace:installed:snippet:Hide-download-button": "{\"code\":\"div.x-downloadButton-DownloadButton { display: none; }\",\"title\":\"Hide download button\",\"description\":\"Hide download button in EPs and albums\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-download-button.png\"}",
  "marketplace:installed-snippets": "[\"marketplace:installed:snippet:Hide-liked-songs-card\",\"marketplace:installed:snippet:Remove-Popular-sections-from-homepage\",\"marketplace:installed:snippet:Hide-friends-activity-button\",\"marketplace:installed:snippet:Hide-podcast-tab\",\"marketplace:installed:snippet:Hide-play-count\",\"marketplace:installed:snippet:Hide-recent-searches\",\"marketplace:installed:snippet:Hide-download-button\",\"marketplace:installed:snippet:Fix-now-playing-icon-color\",\"marketplace:installed:snippet:Auto-hide-Friends\",\"marketplace:installed:snippet:Hide-now-playing-view-button\",\"marketplace:installed:snippet:Remove-recently-played-from-homepage\"]",
  "marketplace:installed:snippet:Hide-recent-searches": "{\"code\":\".search-searchBrowse-SearchBrowse > section {display: none;}\",\"title\":\"Hide recent searches\",\"description\":\"Hides the recent searches section on the search page\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-recent-searches.png\"}",
  "marketplace:installed:snippet:Hide-liked-songs-card": "{\"code\":\".collection-collectionEntityHeroCard-likedSongs{ display: none; }\",\"title\":\"Hide liked songs card\",\"description\":\"Hides the sometimes unfitting liked Songs card in the Your Libary tab\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-likedSongs-card.png\"}",
  "marketplace:albumArtBasedColors": "false",
  "marketplace:installed:spicetify/spicetify-cli/Extensions/trashbin.js": "{\"manifest\":{\"name\":\"Trash Bin\",\"description\":\"Throw songs/artists to trash bin and never hear them again (automatically skip). This extension will append a Throw to Trashbin option in tracks and artists link right click menu.\",\"preview\":\"https://i.imgur.com/ZFTy5Rm.png\",\"main\":\"Extensions/trashbin.js\"},\"type\":\"extension\",\"title\":\"Trash Bin\",\"subtitle\":\"Throw songs/artists to trash bin and never hear them again (automatically skip). This extension will append a Throw to Trashbin option in tracks and artists link right click menu.\",\"authors\":[{\"name\":\"spicetify\",\"url\":\"https://github.com/spicetify\"}],\"user\":\"spicetify\",\"repo\":\"spicetify-cli\",\"branch\":\"master\",\"imageURL\":\"https://i.imgur.com/ZFTy5Rm.png\",\"extensionURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-cli/master/Extensions/trashbin.js\",\"readmeURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-cli/master/undefined\",\"stars\":16365,\"lastUpdated\":\"2024-03-23T00:46:03Z\",\"created\":\"2018-12-01T19:55:18Z\"}",
  "marketplace:tags": "false",
  "marketplace:installed-themes": "[\"marketplace:installed:JulienMaille/spicetify-dynamic-theme/user.css\"]",
  "marketplace:active-tab": "Extensions",
  "marketplace:local-theme": "marketplace",
  "marketplace:installed:snippet:Hide-friends-activity-button": "{\"code\":\"button.encore-over-media-set.main-topBar-buddyFeed {display: none;}\",\"title\":\"Hide friends activity button\",\"description\":\"Hides the friends activity button next to your profile picture\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-friends-activity-button.png\"}",
  "marketplace:installed:snippet:Hide-podcast-tab": "{\"code\":\"[href='/collection/podcasts'] {display: none;}\",\"title\":\"Hide podcast tab\",\"description\":\"Hides the podcast tab in Your Library\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-podcast-tab.png\"}",
  "marketplace:albumArtBasedColorsMode": "monochromeDark",
  "marketplace:installed:snippet:Remove-recently-played-from-homepage": "{\"code\":\"section.main-shelf-shelf[aria-label='Recently played'] { visibility: hidden; position: absolute; }\",\"title\":\"Remove recently played from homepage\",\"description\":\"Removes the recently played shelf from the home page\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/remove-recently-played.png\"}",
  "marketplace:installed:theRealPadster/spicetify-hide-podcasts/hidePodcasts.js": "{\"manifest\":{\"name\":\"Spicetify-Hide-Podcasts\",\"description\":\"Spicetify extension to hide podcasts.\",\"preview\":\"screenshot.png\",\"main\":\"hidePodcasts.js\",\"readme\":\"README.md\"},\"type\":\"extension\",\"title\":\"Spicetify-Hide-Podcasts\",\"subtitle\":\"Spicetify extension to hide podcasts.\",\"authors\":[{\"name\":\"theRealPadster\",\"url\":\"https://github.com/theRealPadster\"}],\"user\":\"theRealPadster\",\"repo\":\"spicetify-hide-podcasts\",\"branch\":\"main\",\"imageURL\":\"https://raw.githubusercontent.com/theRealPadster/spicetify-hide-podcasts/main/screenshot.png\",\"extensionURL\":\"https://raw.githubusercontent.com/theRealPadster/spicetify-hide-podcasts/main/hidePodcasts.js\",\"readmeURL\":\"https://raw.githubusercontent.com/theRealPadster/spicetify-hide-podcasts/main/README.md\",\"stars\":234,\"lastUpdated\":\"2023-12-01T22:38:49Z\",\"created\":\"2020-10-10T02:48:23Z\"}",
  "marketplace:installed:snippet:Hide-play-count": "{\"code\":\".main-trackList-playsHeader,.main-trackList-rowPlayCount {display: none}\",\"title\":\"Hide play count\",\"description\":\"Hides the play count on songs/albums etc so you can give each songs its chance without thinking about numbers\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/hide-play-count.png\"}",
  "marketplace:installed:Tetrax-10/Spicetify-Extensions/Image-Opener/imageOpener.js": "{\"manifest\":{\"name\":\"Image Opener\",\"description\":\"Opens high res image of tracks, artists, playlists, profiles etc...\",\"preview\":\"Image-Opener/preview.png\",\"main\":\"Image-Opener/imageOpener.js\",\"readme\":\"Image-Opener/README.md\",\"branch\":\"dist\"},\"type\":\"extension\",\"title\":\"Image Opener\",\"subtitle\":\"Opens high res image of tracks, artists, playlists, profiles etc...\",\"authors\":[{\"name\":\"Tetrax-10\",\"url\":\"https://github.com/Tetrax-10\"}],\"user\":\"Tetrax-10\",\"repo\":\"Spicetify-Extensions\",\"branch\":\"dist\",\"imageURL\":\"https://raw.githubusercontent.com/Tetrax-10/Spicetify-Extensions/dist/Image-Opener/preview.png\",\"extensionURL\":\"https://raw.githubusercontent.com/Tetrax-10/Spicetify-Extensions/dist/Image-Opener/imageOpener.js\",\"readmeURL\":\"https://raw.githubusercontent.com/Tetrax-10/Spicetify-Extensions/dist/Image-Opener/README.md\",\"stars\":142,\"lastUpdated\":\"2023-07-22T15:27:40Z\",\"created\":\"2022-05-22T08:27:58Z\"}",
  "marketplace:installed:duffey/spicetify-playlist-labels/dist/spicetify-playlist-labels.js": "{\"manifest\":{\"name\":\"Playlist Labels\",\"description\":\"Adds interactive playlist labels to your tracklist\",\"preview\":\"preview.png\",\"main\":\"dist/spicetify-playlist-labels.js\",\"readme\":\"README.md\",\"authors\":[{\"name\":\"Scott Duffey\",\"url\":\"https://github.com/duffey\"}],\"tags\":[\"playlist\",\"label\",\"tag\",\"tracklist\"]},\"type\":\"extension\",\"title\":\"Playlist Labels\",\"subtitle\":\"Adds interactive playlist labels to your tracklist\",\"authors\":[{\"name\":\"Scott Duffey\",\"url\":\"https://github.com/duffey\"}],\"user\":\"duffey\",\"repo\":\"spicetify-playlist-labels\",\"branch\":\"master\",\"imageURL\":\"https://raw.githubusercontent.com/duffey/spicetify-playlist-labels/master/preview.png\",\"extensionURL\":\"https://raw.githubusercontent.com/duffey/spicetify-playlist-labels/master/dist/spicetify-playlist-labels.js\",\"readmeURL\":\"https://raw.githubusercontent.com/duffey/spicetify-playlist-labels/master/README.md\",\"stars\":22,\"lastUpdated\":\"2024-04-21T14:51:44Z\",\"created\":\"2023-11-09T10:34:19Z\"}",
  "marketplace:stars": "false",
  "marketplace:installed:snippet:Auto-hide-Friends": "{\"code\":\"[aria-label='Friend Activity'] {\\n  transition: width 0.3s;\\n}\\n@media screen and (max-width: 1200px) {\\n  [aria-label='Friend Activity'] {\\n    width: 0;\\n  }\\n  [aria-label='Friend Activity'] .LayoutResizer__resize-bar {\\n    display: none;\\n  }\\n}\",\"title\":\"Auto-hide Friends\",\"description\":\"Collapse the friends activity sidebar on small screens\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/auto-hide-friends.png\"}",
  "marketplace:theme-installed": "marketplace:installed:JulienMaille/spicetify-dynamic-theme/user.css",
  "marketplace:albumArtBasedColorsVibrancy": "desaturated"
}
```
</details>

I've already reset setiing few times, it didn't help.
Tried to reinstall spicetify from scratch, then add only Playlist labels extension - it didn't help either.

Playlists still looks like these:
![изображение](https://github.com/duffey/spicetify-playlist-labels/assets/24671137/220516af-2947-4ab0-9291-6cf2a33f9798)

**Comment by duffey** [comment] 2024-04-24 11:50
Please refer to the this issue below for updates.

Duplicate of #25

**Closed by duffey** 2024-04-24 11:50 UTC
